steps:
- name: gcr.io/cloud-builders/docker
  args:
    - build
    - '-t'
    - 'europe-north1-docker.pkg.dev/ti-dictionary/$REPO_NAME/tid-test'
    - .
    - '-f'
    - demonstrator/test/Dockerfile
  id: Build
- name: 'gcr.io/cloud-builders/docker'
  args:
    - push
    - 'europe-north1-docker.pkg.dev/ti-dictionary/tid-docker-repository/tid-test'
  id: Push
images:
  - 'europe-north1-docker.pkg.dev/ti-dictionary/tid-docker-repository/tid-test'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  REPO_NAME: tid-docker-repository
  PROJECT_ID: ti-dictionary
  _GCR_HOSTNAME: eu.gcr.io
  _PLATFORM: managed
  _LABELS: gcb-trigger-id=2cac9029-a121-4a64-a9a6-9459f59d971f
  _TRIGGER_ID: 2cac9029-a121-4a64-a9a6-9459f59d971f
  _SERVICE_NAME: tid-demonstrator-frontend
  _DEPLOY_REGION: europe-north1