steps:
- name: gcr.io/cloud-builders/docker
  args:
    - build
    - '-t'
    - '$_DEPLOY_REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$TRIGGER_NAME'
    - .
    - '-f'
    - $_DOCKERFILE_PATH/Dockerfile
  id: Build
- name: 'gcr.io/cloud-builders/docker'
  args:
    - push
    - '$_DEPLOY_REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$TRIGGER_NAME'
  id: Push
images:
  - '$_DEPLOY_REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$TRIGGER_NAME:$COMMIT_SHA'