name: transparency_tracing

services:
    jaeger:
        image: jaegertracing/opentelemetry-all-in-one:latest
        environment:
            - JAEGER_SERVICE_PORT_ZIPKIN_ENDPOINT
        hostname: "${JAEGER_SERVICE_HOST}"
        networks:
            - tt
        ports:
            - "5775:5775" # accept zipkin.thrift over compact thrift protocol
            - "5778:5778" # serve configs
            - "6831:6831" # accept jaeger.thrift over compact thrift protocol
            - "6832:6832" # accept jaeger.thrift over binary thrift protocol
            - "9411:9411" # Zipkin compatible endpoint
            - "14250:14250" # accept model.proto
            - "14268:14268" # accept jaeger.thrift directly from clients
            - "14269:14269" # admin port: health check at / and metrics at /metrics
            - "${JAEGER_SERVICE_PORT_GRPC}:16685" # Protobuf/gRPC QueryService
            - "16686:16686" # serve frontend
    otelcollector:
        build:
            context: .
            dockerfile: demonstrator/otelcollector/Dockerfile
        image: otelcollector
        hostname: "${OTELCOLLECTOR_SERVICE_HOST}"
        #        volumes:
        #            # to export traces in a json file
        #            - type: bind
        #              source: ./traces
        #              target: /traces
        networks:
            - tt
        ports:
            - "1888:1888" # pprof extension
            - "13133:13133" # health_check extension
            - "4317:4317" # OTLP gRPC receiver
            - "4318:4318" # OTLP http receiver
            - "55679:55679" # zpages extension: http://localhost:55679/debug/servicez
        depends_on:
            - jaeger
    email_service:
        build:
            context: .
            dockerfile: demonstrator/emailservice/Dockerfile
        #            dockerfile: demonstrator/email_service/Dockerfile_wt  # for performance measurements
        image: email_service
        environment:
            - OTELCOLLECTOR_SERVICE_PORT_OTLP_RECEIVER
            - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
            - OTEL_RESOURCE_ATTRIBUTES=service.name=emailservice
        hostname: "${EMAILSERVICE_SERVICE_HOST}"
        networks:
            - tt
        ports:
            - "${EMAILSERVICE_SERVICE_PORT}:${EMAILSERVICE_SERVICE_PORT}"
        depends_on:
            - jaeger
            - otelcollector
    account_service:
        build:
            context: .
            dockerfile: demonstrator/accountservice/Dockerfile
        #            dockerfile: demonstrator/account_service/Dockerfile_wt  # for performance measurements
        image: account_service
        environment:
            - ACCOUNTSERVICE_SERVICE_PORT
            - EMAILSERVICE_SERVICE_HOST
            - EMAILSERVICE_SERVICE_PORT
            - OTELCOLLECTOR_SERVICE_PORT_OTLP_RECEIVER
            - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
            - OTEL_RESOURCE_ATTRIBUTES=service.name=accountservice
        hostname: "${ACCOUNTSERVICE_SERVICE_HOST}"
        networks:
            - tt
        ports:
            - "${ACCOUNTSERVICE_SERVICE_PORT}:${ACCOUNTSERVICE_SERVICE_PORT}"
        depends_on:
            - jaeger
            - otelcollector
            - email_service
    courier_service:
        build:
            context: .
            dockerfile: demonstrator/courierservice/Dockerfile
        #            dockerfile: demonstrator/courier_service/Dockerfile_wt  # for performance measurements
        image: courier_service
        environment:
            - COURIERSERVICE_SERVICE_PORT
            - EMAILSERVICE_SERVICE_HOST
            - EMAILSERVICE_SERVICE_PORT
            - ACCOUNTSERVICE_SERVICE_HOST
            - ACCOUNTSERVICE_SERVICE_PORT
            - OTELCOLLECTOR_SERVICE_PORT_OTLP_RECEIVER
            - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
            - OTEL_RESOURCE_ATTRIBUTES=service.name=courierservice
        hostname: "${COURIERSERVICE_SERVICE_HOST}"
        networks:
            - tt
        ports:
            - "${COURIERSERVICE_SERVICE_PORT}:${COURIERSERVICE_SERVICE_PORT}"
        depends_on:
            - jaeger
            - otelcollector
            - email_service
            - account_service
    frontend:
        build:
            context: .
            dockerfile: demonstrator/frontend/Dockerfile
        #            dockerfile: demonstrator/frontend/Dockerfile_wt  # for performance measurements
        image: frontend
        environment:
            - ACCOUNTSERVICE_SERVICE_HOST
            - ACCOUNTSERVICE_SERVICE_PORT
            - COURIERSERVICE_SERVICE_HOST
            - COURIERSERVICE_SERVICE_PORT
            - OTELCOLLECTOR_SERVICE_PORT_OTLP_RECEIVER
            - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
            - OTEL_RESOURCE_ATTRIBUTES=service.name=frontend
        hostname: "${FRONTEND_SERVICE_HOST}"
        networks:
            - tt
        ports:
            - "${FRONTEND_SERVICE_PORT}:${FRONTEND_SERVICE_PORT}"
        depends_on:
            - jaeger
            - otelcollector
            - account_service
            - courier_service
    tidservice:
        build:
            context: .
            dockerfile: tid-service/Dockerfile
        image: tidservice
        environment:
            - JAEGER_SERVICE_HOST
            - JAEGER_SERVICE_PORT_GRPC
            - FRONTEND_SERVICE_HOST # for integration test
            - FRONTEND_SERVICE_PORT # for integration test
            - ACCOUNTSERVICE_SERVICE_HOST # for integration test
            - ACCOUNTSERVICE_SERVICE_PORT # for integration test
            - COURIERSERVICE_SERVICE_HOST # for integration test
            - COURIERSERVICE_SERVICE_PORT # for integration test
            - EMAILSERVICE_SERVICE_HOST # for integration test
            - EMAILSERVICE_SERVICE_PORT # for integration test
            - TIDSERVICE_SERVICE_HOST
            - TIDSERVICE_SERVICE_PORT
            - TI_DICTIONARY_NAME
        volumes:
            # - type: bind                    # for development only
            #   source: tid-service
            #   target: /services/tidservice
            #   read_only: true
            - type: bind
              source: ./dictionary
              target: /services/dictionary
              read_only: true
        hostname: "${TIDSERVICE_SERVICE_HOST}"
        networks:
            - tt
        ports:
            - "${TIDSERVICE_SERVICE_PORT}:${TIDSERVICE_SERVICE_PORT}"

networks:
    tt:
